export const CATEGORIES_GET = 'CATEGORIES_GET';
export const CATEGORIES_GET_FINISHED = 'CATEGORIES_GET_FINISHED';
export const POSTS_GET = 'POSTS_GET';
export const POSTS_GET_FINISHED = 'POSTS_GET_FINISHED';
